export type Category = {
  id: number;
  parentId?: number;
  name: string;
  isIncome?: boolean;
}

export const DEFAULT_CATEGORIES = [
  { id: 1, name: 'Auto & Transport' },
  { id: 2, name: 'Bills & Utilities' },
  { id: 3, name: 'Business Services' },
  { id: 4, name: 'Education' },
  { id: 5, name: 'Entertainment' },
  { id: 6, name: 'Fees & Charges' },
  { id: 7, name: 'Financial' },
  { id: 8, name: 'Food & Dining' },
  { id: 9, name: 'Gifts & Donations' },
  { id: 10, name: 'Health & Fitness' },
  { id: 11, name: 'Home' },
  { id: 12, name: 'Income', isIncome: true },
  { id: 13, name: 'Kids' },
  { id: 14, name: 'Misc. Expenses' },
  { id: 15, name: 'Personal Care' },
  { id: 16, name: 'Pets' },
  { id: 17, name: 'Shopping' },
  { id: 18, name: 'Taxes' },
  { id: 19, name: 'Transfer' },
  { id: 20, name: 'Travel' },
  { id: 21, parentId: 1, name: 'Auto Insurance' },
  { id: 22, parentId: 1, name: 'Auto Payment' },
  { id: 23, parentId: 1, name: 'Gas & Fuel' },
  { id: 24, parentId: 1, name: 'Parking' },
  { id: 25, parentId: 1, name: 'Public Transportation' },
  { id: 26, parentId: 1, name: 'Ride Share' },
  { id: 27, parentId: 1, name: 'Service & Parts' },
  { id: 28, parentId: 2, name: 'Electricity' },
  { id: 29, parentId: 2, name: 'Gas' },
  { id: 30, parentId: 2, name: 'Internet' },
  { id: 31, parentId: 2, name: 'Home Phone' },
  { id: 32, parentId: 2, name: 'Mobile Phone' },
  { id: 33, parentId: 3, name: 'Advertising' },
  { id: 34, parentId: 3, name: 'Legal' },
  { id: 35, parentId: 3, name: 'Office Suplies' },
  { id: 36, parentId: 3, name: 'Postage' },
  { id: 37, parentId: 3, name: 'Printing' },
  { id: 38, parentId: 3, name: 'Shipping' },
  { id: 39, parentId: 4, name: 'Books & Supplies' },
  { id: 40, parentId: 4, name: 'Field Trips' },
  { id: 41, parentId: 4, name: 'Student Loans' },
  { id: 43, parentId: 4, name: 'Amusement' },
  { id: 44, parentId: 4, name: 'Arts' },
  { id: 45, parentId: 4, name: 'Movies & DVDs' },
  { id: 46, parentId: 4, name: 'Music' },
  { id: 47, parentId: 4, name: 'Newspapers & Magazines' },
  { id: 48, parentId: 4, name: 'Television' },
  { id: 49, parentId: 5, name: '' },
]
